# Generated by Django 5.2 on 2025-07-06 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('date_found', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBursaryMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('bursary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matches', to='bursaryDataMiner.bursary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bursary_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
