# Generated by Django 5.2 on 2025-08-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryDataMiner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
