# Generated by Django 5.2 on 2025-08-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryDataMiner', '0002_bursary_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='application_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
