# Generated by Django 5.2 on 2025-08-24 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryDataMiner', '0003_bursary_application_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BursaryEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bursary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='bursaryDataMiner.bursary')),
            ],
        ),
    ]
