# Generated by Django 5.2 on 2025-08-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryDataMiner', '0004_bursaryembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursaryembedding',
            name='vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
