# Generated by Django 5.2 on 2025-08-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryDataMiner', '0005_alter_bursaryembedding_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbursarymatch',
            name='match_quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbursarymatch',
            name='relevance_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
