# Generated by Django 5.2 on 2025-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaryDataMiner', '0006_userbursarymatch_match_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbursarymatch',
            name='match_quality',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
