# Generated by Django 5.2 on 2025-08-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualificationsAndCourses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifications',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/id/'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/photos/'),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='documents/transcripts/'),
        ),
    ]
